<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Minecraft",
    "slogan": "www.recandplay.cz",
    "description": "Tento server spad\u00e1 pod projekt R&amp;P. V\u00edce informac\u00ed na hlavn\u00ed str\u00e1nce o projektu.",
    "footer": "All rights reserved - \u00a9 2014-2016 Rec &amp; Play | Kop\u00edrov\u00e1n\u00ed obsahu a prvk\u016f z tohoto webu, pouze s p\u00edsemn\u00fdm povolen\u00edm autora!",
    "language": "cs_CZ",
    "locale": "cs_CZ",
    "timezone": "Europe\/Berlin",
    "theme": "minecraft",
    "adminTheme": "default",
    "homepage": "",
    "postsperpage": "3",
    "uriPost": "\/post\/",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "url": "http:\/\/recandplay.cz\/servers\/Minecraft\/",
    "emailFrom": "no-reply@recandplay.cz",
    "currentBuild": "20160620",
    "twitter": "",
    "facebook": "",
    "googlePlus": "",
    "instagram": "",
    "github": "",
    "dateFormat": "d.m.Y \/ H:i:s",
    "uriBlog": "\/blog\/"
}